<?php
/**
 * @file
 */

/**
 * Implements hook_help().
 */
function stanford_jira_exposed_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';
     */
    case 'admin/help#stanford_jira_exposed':
      return '<p>' . t('Contact your site administrator.') . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function stanford_jira_exposed_menu() {
  /*
   *$items['blog'] = array(
   *  'title' => 'blogs',
   *  'page callback' => 'blog_page',
   *  'access arguments' => array('access content'),
   *  'type' => MENU_SUGGESTED_ITEM,
   *);
   */

  return $items;
}

/**
 * Implements hook_block_info().
 */
function stanford_jira_exposed_block_info() {

  $blocks['testone'] = array(
    'info' => t(''),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function stanford_jira_exposed_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'testone':
      $block['subject'] = t('Test');
      // $block['content'] =
      stanford_jira_exposed_block_testone_view($block);
      break;

  }
  return $block;
}

/**
 * Generates the content for the testone block.
 * @param  [type] &$block [description]
 * @return [type]         [description]
 */
function stanford_jira_exposed_block_testone_view(&$block) {

}
